Merge into qa
ingrithsantamaria/campFour-playwright pull request #1
Opened 2024-12-16 21:46 UTC by ingrithsantamaria

1. Open the site https://demo.spreecommerce.org/
2. Type valid email
3. Type valid password
4. Type valid password Confirmation
5. Click on Login button

2024-12-19 14:07 UTC, NellyAndreina approved these changes

2024-12-19 17:20 UTC, danielmartinezap requested changes

2024-12-19 17:20 UTC, danielmartinezap commented on playwright-report/trace/xtermModule.DSXBckUd.css
Remove all autogerated report files

2024-12-19 17:20 UTC, danielmartinezap commented on README.md
> +## Automation estructure
Automation structure

2024-12-19 17:20 UTC, danielmartinezap commented on README.md
> +Gemini is used as a guide to identify how to use the same method when the selector on mobile is different from the desktop.
Add how reporting is being handled

2024-12-19 17:20 UTC, danielmartinezap commented on playwright/e2e/tests/register/registerTest.spec.js
> +    await registerPage.signUp();
Add assertions to verify the test result (e.g., check if the user is successfully registered by asserting some specific page elements or notifications or even network calls).

2024-12-19 17:20 UTC, danielmartinezap commented on playwright/e2e/pages/register/registerPage.js
> +  constructor(page) {
abstract the selectors to a different file

2024-12-19 17:20 UTC, danielmartinezap commented on playwright/e2e/pages/register/registerPage.js
> +    await this.page.goto("https://demo.spreecommerce.org");
Create a data file for urls

2024-12-19 17:20 UTC, danielmartinezap commented on playwright/e2e/pages/register/registerPage.js
> +    const isMobile = this.page.viewportSize().width < 768
Investigate a different approach to determine Mobile like User-Agent

2024-12-20 20:50 UTC, danielmartinezap commented on playwright-report/data/dbaae40c52718850c8c9366fbeb128a0f7cbc2d7.zip
Remove this one as well

2025-01-07 20:24 UTC, danielmartinezap approved these changes

2025-01-08 00:33 UTC, merged